/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.31.5.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import { anyApi } from "convex/server";

export const api = anyApi;
